# personnaliser le site à votre marque en remplaçant
# nom_intuition par le nom de votre intuition
# mon_equipe par le nom de votre équipe
# 
intuition: Application de Tutorat ITI
nom_equipe: vlaguetteandco
code_equipe: 1B

theme: jekyll-theme-dinky
